### ISSUE TITLE
boot loop on lenovo yoga6 13alc6 ryzen 7 5700u

### ISSUE THREAD

**Issue by halfmoonslash** [1OldSWguy/Lenovo-Yoga6-13ABR8#1]
everithing seem fine, working touchpad and touchscreen, working lan but not on wifi because currently use realtek wifi 6 card,, (already added new smbios, and edit efi for 8c cpu) but after installing and downloading, here take some several boot when procedd to macos intaller,the apple logo appear at the center then when the bar reach almost 3/4 bar, then reboot again, Idk why and how to fix them, the result is bootloop -_- , I've tried to set in config "securebotmode1 = Disabled" but the result is all black screen, then when go back to securebootmode1=default  the result is logo and 3/4 loading bar then bootloop

but im using wd sn530 nvme ssd ... do I need to change the drive ?

**Comment by halfmoonslash** [comment]
problem solve, change quirks>DisableSecurityPolicy=true, now everything workfine but I can login my icloud how to fix them lol

**Comment by halfmoonslash** [comment]
> problem solve, change quirks>DisableSecurityPolicy=true, now everything workfine but I can login my icloud how to fix them lol

it say cannot coomunicate with the server
![Uploading 17302659902824044051650595258574.jpg…]()

**Comment by 1OldSWguy** [comment]
See the Troubleshooting in this section of the OpenCore Post-Install guide

[https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#special-notes-with-securebootmodel](https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#special-notes-with-securebootmodel)

I had this happen on one of my installs. Otherwise it could be the SSD.

**Comment by halfmoonslash** [comment]
> See the Troubleshooting in this section of the OpenCore Post-Install guide
> 
> https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#special-notes-with-securebootmodel
> 
> I had this happen on one of my installs. Otherwise it could be the SSD.

thanks sir, now everything work but some time got freeze idk why, then wifi ax210 cant connect to hidden network due to AirportItlwm.kext bugs, change to itwln.kext duet with heliport for itwln everything work fine,including login to icloud, thanks dude I really apreciated, best regard from indonesia
